remove probe.  version 2.5.3
dnsdb/dnsdbq pull request #173
Opened 2021-03-09 02:07 UTC by djw1149

2021-03-09 03:47 UTC, vixie commented
if we remove probe, then we should make the system "dnsdb" a synonym for "dnsdb2", and add "dnsdb1" to indicate the older pre-SAF version. otherwise dnsdb2 will likely not get much exercise by users with older dnsdbq config files.

2021-03-09 19:08 UTC, djw1149 commented
Pushed switch a change.
Also restructured the man page a bit.

2021-03-11 00:16 UTC, vixie requested changes

2021-03-11 00:16 UTC, vixie commented on dnsdbq.man
> +.Op Fl n Ar name`
why is there a backtick (`) here?

2021-03-11 00:37 UTC, djw1149 commented on dnsdbq.man
> +.Op Fl n Ar name`
A stray character.  Removed and pushed.

2021-03-11 03:01 UTC, merged