Issue183
dnsdb/dnsdbq pull request #184
Opened 2021-06-20 18:29 UTC by vixie

closes #183

2021-06-20 19:49 UTC, djw1149 requested changes
I don't like the hidden -0 command line option.  Is it debug code left in the commit?

2021-06-21 17:18 UTC, vixie commented
how about now?

2021-06-21 17:20 UTC, djw1149 commented
Ok.  Fine to merge

2021-06-21 17:20 UTC, djw1149 approved these changes

2021-06-21 17:24 UTC, merged